#!/usr/bin/ruby

require 'set'

module AdventOfCode
  module D14
    class Reindeer
      attr_reader :name, :speed, :time, :slack_time, :points

      def initialize(name, speed, time, slack_time)
        @name = name
        @speed = speed
        @time = time
        @slack_time = slack_time
        @points = 0
      end

      def self.parse(s)
        m = /^(\S+) can fly (\d+) km\/s for (\d+).*for (\d+)/.match s
        raise 'Invalid' unless m
        new(m[1], m[2].to_i, m[3].to_i, m[4].to_i)
      end

      def distance(secs)
        chunk_size = @time + @slack_time
        chunks = secs / chunk_size
        remainder = secs % chunk_size
        seconds = chunks * @time + ((remainder < @time) ? remainder : @time)
        seconds * @speed
      end

      def add_point
        @points += 1
      end
    end

    class Scorer
      def initialize(list)
        @list = list
      end

      def run(secs)
        (1..secs).each do |t|
          distances = @list.map { |r| [r, r.distance(t)] }
          farthest = distances.max { |a, b| a[1] <=> b[1] }
          distances.select { |r| r[1] == farthest[1] }.each do |r|
            r[0].add_point
          end
        end
      end
    end
  end
end

def script(seconds)
  seconds = seconds.to_i
  reindeer = []
  $stdin.each_line do |line|
    reindeer << AdventOfCode::D14::Reindeer.parse(line)
  end
  distance = reindeer.map { |r| r.distance(seconds) }.max
  sc = AdventOfCode::D14::Scorer.new(reindeer)
  sc.run(seconds)
  max_points = reindeer.map { |r| r.points }.max
  puts "Furthest distance is: #{distance}"
  puts "Max points is: #{max_points}"
  return 0
end

exit script(*ARGV) if __FILE__ == $0
