#!/usr/bin/ruby

require 'set'

module AdventOfCode
  module D19
    class Replacer
      attr_reader :replacements

      def initialize(replacements)
        @replacements = replacements
      end

      def self.parse(s)
        replacements = {}
        s.each_line do |line|
          /^(\w+) => (\w+)/.match(line) do |m|
            replacements[m[1]] ||= []
            replacements[m[1]] << m[2]
          end
        end
        new(replacements)
      end

      def combinations(s)
        results = Set.new
        re = Regexp.new replacements.keys.map { |k| Regexp.escape(k) }.join('|')
        s.length.times do |offset|
          re.match(s, offset) do |m|
            b, e = m.offset(0)
            next if b != offset
            chemical = m[0]
            @replacements[chemical].each do |r|
              t = s.dup
              t[b...e] = r
              results << t
            end
          end
        end
        results
      end

      def derive(s)
        # Reverse the strings so that we can match from the right, since this is
        # an unambiguous grammar.
        reverse = {}
        start = replacements['e'].map { |str| str.reverse }
        replacements.each do |k, v|
          v.each { |p| reverse[p.reverse] = k.reverse if k != 'e' }
        end
        re = Regexp.new reverse.keys.map { |k| Regexp.escape(k) }.join('|')
        steps = 0
        t = s.reverse
        until start.include? t
          t.sub!(re, reverse)
          steps += 1
        end
        steps + 1
      end
    end
  end
end

def script
  state = $stdin.read
  rules, pattern = state.split("\n\n")
  pattern.chomp!
  rep = AdventOfCode::D19::Replacer.parse(rules)
  puts "Number of distinct molecules: #{rep.combinations(pattern).length}"
  puts "Number of steps required: #{rep.derive(pattern)}"
  return 0
end

exit script(*ARGV) if __FILE__ == $0
