#!/usr/bin/ruby

module AdventOfCode
  module D2
    class Present
      def initialize(d1, d2, d3)
        @dimensions = [d1, d2, d3].sort
      end

      def slack
        d1 * d2
      end

      def surface_area
        2 * (d1 * d2 + d2 * d3 + d1 * d3)
      end

      def volume
        d1 * d2 * d3
      end

      def total_paper
        surface_area + slack
      end

      def shortest_distance
        2 * (d1 + d2)
      end

      def total_ribbon
        shortest_distance + volume
      end

      private

      def d1
        @dimensions[0]
      end

      def d2
        @dimensions[1]
      end

      def d3
        @dimensions[2]
      end
    end
  end
end

def script(*_args)
  paper = 0
  ribbon = 0
  while line = gets
    raise "Invalid line" unless /^(\d+)x(\d+)x(\d+)/.match line
    p = AdventOfCode::D2::Present.new(*Regexp.last_match[1..3].map(&:to_i))
    paper += p.total_paper
    ribbon += p.total_ribbon
  end
  puts "Total square feet of paper needed: #{paper}"
  puts "Total feet of ribbon needed: #{ribbon}"
  return 0
end

exit script(ARGV) if __FILE__ == $0
