#!/usr/bin/ruby

require 'digest'

module AdventOfCode
  module D4
    class Miner
      def initialize(key, nzeros)
        @key = key
        @re = Regexp.new('^' + ('0' * nzeros))
        @counter = 1
      end

      def mine
        loop do
          data = @key + @counter.to_s
          hash = Digest::MD5.hexdigest(data)
          this = @counter
          @counter += 1
          if @re.match hash
            return [this, hash]
          end
        end
      end
    end
  end
end

def script(args)
  p = AdventOfCode::D4::Miner.new(args[0], args[1].to_i)
  count = p.mine[0]
  puts "Answer is: #{count}"
  return 0
end

exit script(ARGV) if __FILE__ == $0
